ENV: local
Name: car-record
Host: localhost
Port: 8081
FrontEndDir: ./app/.quasar-project/dist/spa
ConnectionStrings:
  Mysql:
    Host: localhost
    Port: 3306
    Database: car-project
    User: user
    Password: 1234Qwer
