// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entities "car-record/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VehicleUsecase is an autogenerated mock type for the VehicleUsecase type
type VehicleUsecase struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, userID, name, license, company, model
func (_m *VehicleUsecase) Add(ctx context.Context, userID uint, name string, license string, company string, model string) error {
	ret := _m.Called(ctx, userID, name, license, company, model)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, string, string) error); ok {
		r0 = rf(ctx, userID, name, license, company, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *VehicleUsecase) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Edit provides a mock function with given fields: ctx, userID, vehicle
func (_m *VehicleUsecase) Edit(ctx context.Context, userID uint, vehicle entities.VehicleDetail) error {
	ret := _m.Called(ctx, userID, vehicle)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, entities.VehicleDetail) error); ok {
		r0 = rf(ctx, userID, vehicle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *VehicleUsecase) Get(ctx context.Context, id uint) (entities.VehicleDetail, error) {
	ret := _m.Called(ctx, id)

	var r0 entities.VehicleDetail
	if rf, ok := ret.Get(0).(func(context.Context, uint) entities.VehicleDetail); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.VehicleDetail)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, userID
func (_m *VehicleUsecase) GetList(ctx context.Context, userID uint) ([]entities.Vehicle, error) {
	ret := _m.Called(ctx, userID)

	var r0 []entities.Vehicle
	if rf, ok := ret.Get(0).(func(context.Context, uint) []entities.Vehicle); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Vehicle)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewVehicleUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewVehicleUsecase creates a new instance of VehicleUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVehicleUsecase(t mockConstructorTestingTNewVehicleUsecase) *VehicleUsecase {
	mock := &VehicleUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
